[project]
name = "quality-annotation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogluon[tabular]>=1.5.0",
    "black>=25.12.0",
    "datasets>=4.0.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]
